const superPowers = {
	USER_CREATOR: 'USER_CREATOR',
	USER_EDITOR: 'USER_EDITOR',
	USER_VIEWER: 'USER_VIEWER',
	CHECKING: 'CHECKING',
	TICKET_VIEWER: 'TICKET_VIEWER',
	TICKET_EDITOR: 'TICKET_EDITOR',
	CHANGE_MY_PASSWORD: 'CHANGE_MY_PASSWORD',
	VIEW_MY_DATA_BUYER: 'VIEW_MY_DATA_BUYER',
	CHANGE_MY_DATA_BUYER: 'CHANGE_MY_DATA_BUYER',
}

module.exports = superPowers
