const superPowers = {
	USER_CREATOR: 'USER_CREATOR',
	USER_EDITOR: 'USER_EDITOR',
	CHANGE_MY_PASSWORD: 'CHANGE_MY_PASSWORD',
	CHECKING: 'CHECKING',
	VIEW_MY_DATA_BUYER: 'VIEW_MY_DATA_BUYER',
	CHANGE_MY_DATA_BUYER: 'CHANGE_MY_DATA_BUYER',
	USER_VIWER: 'USER_VIWER',
}

module.exports = superPowers
